-- Boîte à idées : plusieurs messages par personne, accès uniquement via RPC token (comme les anecdotes).

CREATE TABLE IF NOT EXISTS public.personne_idees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personne_id bigint NOT NULL REFERENCES public.personnes (id) ON DELETE CASCADE,
  contenu text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT personne_idees_contenu_nonempty CHECK (length(trim(contenu)) > 0),
  CONSTRAINT personne_idees_contenu_max CHECK (char_length(contenu) <= 8000)
);

CREATE INDEX IF NOT EXISTS idx_personne_idees_personne_created
  ON public.personne_idees (personne_id, created_at DESC);

COMMENT ON TABLE public.personne_idees IS
  'Messages « boîte à idées » par invité ; plusieurs par personne ; lecture via token uniquement.';

ALTER TABLE public.personne_idees ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.list_idees_for_token(p_token text, p_personne_id bigint)
 RETURNS TABLE(id bigint, contenu text, created_at timestamptz)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  fam public.familles%ROWTYPE;
BEGIN
  SELECT * INTO fam FROM public.get_famille_by_token(p_token);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invalid_token';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.personnes p
    WHERE p.id = p_personne_id AND p.famille_id = fam.id
  ) THEN
    RAISE EXCEPTION 'personne_not_in_famille';
  END IF;

  RETURN QUERY
  SELECT i.id, i.contenu, i.created_at
  FROM public.personne_idees i
  WHERE i.personne_id = p_personne_id
  ORDER BY i.created_at DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.insert_idee_for_token(p_token text, p_personne_id bigint, p_contenu text)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  fam public.familles%ROWTYPE;
  v_trim text;
  v_id bigint;
BEGIN
  SELECT * INTO fam FROM public.get_famille_by_token(p_token);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invalid_token';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.personnes p
    WHERE p.id = p_personne_id AND p.famille_id = fam.id
  ) THEN
    RAISE EXCEPTION 'personne_not_in_famille';
  END IF;

  v_trim := trim(COALESCE(p_contenu, ''));
  IF length(v_trim) = 0 THEN
    RAISE EXCEPTION 'empty_content';
  END IF;
  IF char_length(v_trim) > 8000 THEN
    RAISE EXCEPTION 'content_too_long';
  END IF;

  INSERT INTO public.personne_idees (personne_id, contenu)
  VALUES (p_personne_id, v_trim)
  RETURNING personne_idees.id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.delete_idee_for_token(p_token text, p_idee_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  fam public.familles%ROWTYPE;
BEGIN
  SELECT * INTO fam FROM public.get_famille_by_token(p_token);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invalid_token';
  END IF;

  DELETE FROM public.personne_idees i
  WHERE i.id = p_idee_id
    AND EXISTS (
      SELECT 1 FROM public.personnes p
      WHERE p.id = i.personne_id AND p.famille_id = fam.id
    );

  IF FOUND THEN
    RETURN true;
  END IF;
  RETURN false;
END;
$function$;
