-- Anecdotes multiples par personne, visibles uniquement via RPC token (privé à la personne / famille).

CREATE TABLE IF NOT EXISTS public.personne_anecdotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personne_id bigint NOT NULL REFERENCES public.personnes (id) ON DELETE CASCADE,
  contenu text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT personne_anecdotes_contenu_nonempty CHECK (length(trim(contenu)) > 0),
  CONSTRAINT personne_anecdotes_contenu_max CHECK (char_length(contenu) <= 8000)
);

CREATE INDEX IF NOT EXISTS idx_personne_anecdotes_personne_created
  ON public.personne_anecdotes (personne_id, created_at DESC);

COMMENT ON TABLE public.personne_anecdotes IS
  'Anecdotes libres déposées par invité ; plusieurs par personne ; lecture via token uniquement.';

ALTER TABLE public.personne_anecdotes ENABLE ROW LEVEL SECURITY;

-- Pas de politique pour anon/authenticated : accès uniquement via fonctions SECURITY DEFINER.

CREATE OR REPLACE FUNCTION public.list_anecdotes_for_token(p_token text, p_personne_id bigint)
 RETURNS TABLE(id bigint, contenu text, created_at timestamptz)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  fam public.familles%ROWTYPE;
BEGIN
  SELECT * INTO fam FROM public.get_famille_by_token(p_token);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invalid_token';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.personnes p
    WHERE p.id = p_personne_id AND p.famille_id = fam.id
  ) THEN
    RAISE EXCEPTION 'personne_not_in_famille';
  END IF;

  RETURN QUERY
  SELECT a.id, a.contenu, a.created_at
  FROM public.personne_anecdotes a
  WHERE a.personne_id = p_personne_id
  ORDER BY a.created_at DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.insert_anecdote_for_token(p_token text, p_personne_id bigint, p_contenu text)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  fam public.familles%ROWTYPE;
  v_trim text;
  v_id bigint;
BEGIN
  SELECT * INTO fam FROM public.get_famille_by_token(p_token);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invalid_token';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.personnes p
    WHERE p.id = p_personne_id AND p.famille_id = fam.id
  ) THEN
    RAISE EXCEPTION 'personne_not_in_famille';
  END IF;

  v_trim := trim(COALESCE(p_contenu, ''));
  IF length(v_trim) = 0 THEN
    RAISE EXCEPTION 'empty_content';
  END IF;
  IF char_length(v_trim) > 8000 THEN
    RAISE EXCEPTION 'content_too_long';
  END IF;

  INSERT INTO public.personne_anecdotes (personne_id, contenu)
  VALUES (p_personne_id, v_trim)
  RETURNING personne_anecdotes.id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.delete_anecdote_for_token(p_token text, p_anecdote_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  fam public.familles%ROWTYPE;
BEGIN
  SELECT * INTO fam FROM public.get_famille_by_token(p_token);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invalid_token';
  END IF;

  DELETE FROM public.personne_anecdotes a
  WHERE a.id = p_anecdote_id
    AND EXISTS (
      SELECT 1 FROM public.personnes p
      WHERE p.id = a.personne_id AND p.famille_id = fam.id
    );

  IF FOUND THEN
    RETURN true;
  END IF;
  RETURN false;
END;
$function$;
