create extension if not exists "pgjwt" with schema "extensions";

drop extension if exists "pg_net";

create schema if not exists "uploads";

create type "public"."avatar_category" as enum ('skin', 'face_shape', 'eyes', 'nose_shape', 'mouth_shape', 'hair_style', 'hair_color', 'facial_hair', 'accessory', 'hat', 'top', 'bottom');

create sequence "public"."audit_log_id_seq";


  create table "public"."app_secrets" (
    "key" text not null,
    "value" text not null,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."app_secrets" enable row level security;


  create table "public"."audit_log" (
    "id" bigint not null default nextval('public.audit_log_id_seq'::regclass),
    "table_name" text not null,
    "action" text not null,
    "record_id" bigint,
    "user_id" uuid,
    "famille_id" bigint,
    "created_at" timestamp with time zone default now(),
    "metadata" jsonb
      );


alter table "public"."audit_log" enable row level security;


  create table "public"."avatars" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "personne_id" bigint not null,
    "seed" text,
    "options" jsonb not null default '{}'::jsonb,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."avatars" enable row level security;


  create table "public"."familles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "personne_principale" bigint,
    "connexion" timestamp with time zone,
    "auth_uuid" uuid,
    "login_token" text,
    "is_admin" boolean default false,
    "created_by" uuid,
    "rue" text,
    "numero" text,
    "boite" text,
    "cp" text,
    "ville" text,
    "pays" text,
    "post" boolean not null default false
      );


alter table "public"."familles" enable row level security;


  create table "public"."musiques" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "titre" text not null,
    "auteur" text not null,
    "lien" text not null,
    "commentaire" text not null,
    "personne_id" bigint not null,
    "status" text default 'pending'::text
      );


alter table "public"."musiques" enable row level security;


  create table "public"."personnes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "nom" text not null,
    "prenom" text not null,
    "present_reception" boolean not null default false,
    "famille_id" bigint not null,
    "email" text,
    "present_repas" boolean default false,
    "present_soiree" boolean default false,
    "invite_reception" boolean default false,
    "invite_repas" boolean default false,
    "invite_soiree" boolean default false
      );


alter table "public"."personnes" enable row level security;


  create table "uploads"."player_data" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "comment" text default ''::text,
    "image" text default ''::text
      );


alter table "uploads"."player_data" enable row level security;

alter sequence "public"."audit_log_id_seq" owned by "public"."audit_log"."id";

CREATE UNIQUE INDEX app_secrets_pkey ON public.app_secrets USING btree (key);

CREATE UNIQUE INDEX audit_log_pkey ON public.audit_log USING btree (id);

CREATE INDEX avatars_personne_id_idx ON public.avatars USING btree (personne_id);

CREATE UNIQUE INDEX avatars_pkey ON public.avatars USING btree (id);

CREATE UNIQUE INDEX familles_login_token_key ON public.familles USING btree (login_token);

CREATE UNIQUE INDEX familles_pkey ON public.familles USING btree (id);

CREATE INDEX idx_audit_log_table_action ON public.audit_log USING btree (table_name, action, created_at DESC);

CREATE INDEX idx_audit_log_user_id ON public.audit_log USING btree (user_id, created_at DESC);

CREATE UNIQUE INDEX idx_avatars_personne_unique ON public.avatars USING btree (personne_id);

CREATE INDEX idx_familles_auth_uuid_active ON public.familles USING btree (auth_uuid) WHERE (auth_uuid IS NOT NULL);

CREATE INDEX idx_familles_personne_principale ON public.familles USING btree (personne_principale) WHERE (personne_principale IS NOT NULL);

CREATE INDEX idx_musiques_created_at ON public.musiques USING btree (created_at DESC);

CREATE INDEX idx_personnes_famille_id_active ON public.personnes USING btree (famille_id);

CREATE INDEX idx_personnes_nom_prenom ON public.personnes USING btree (nom, prenom);

CREATE INDEX musiques_personne_id_idx ON public.musiques USING btree (personne_id);

CREATE UNIQUE INDEX musiques_pkey ON public.musiques USING btree (id);

CREATE UNIQUE INDEX personnes_pkey ON public.personnes USING btree (id);

CREATE UNIQUE INDEX unique_personne_avatar ON public.avatars USING btree (personne_id);

CREATE UNIQUE INDEX player_data_pkey ON uploads.player_data USING btree (id);

alter table "public"."app_secrets" add constraint "app_secrets_pkey" PRIMARY KEY using index "app_secrets_pkey";

alter table "public"."audit_log" add constraint "audit_log_pkey" PRIMARY KEY using index "audit_log_pkey";

alter table "public"."avatars" add constraint "avatars_pkey" PRIMARY KEY using index "avatars_pkey";

alter table "public"."familles" add constraint "familles_pkey" PRIMARY KEY using index "familles_pkey";

alter table "public"."musiques" add constraint "musiques_pkey" PRIMARY KEY using index "musiques_pkey";

alter table "public"."personnes" add constraint "personnes_pkey" PRIMARY KEY using index "personnes_pkey";

alter table "uploads"."player_data" add constraint "player_data_pkey" PRIMARY KEY using index "player_data_pkey";

alter table "public"."avatars" add constraint "avatars_personne_id_fkey" FOREIGN KEY (personne_id) REFERENCES public.personnes(id) ON DELETE CASCADE not valid;

alter table "public"."avatars" validate constraint "avatars_personne_id_fkey";

alter table "public"."avatars" add constraint "unique_personne_avatar" UNIQUE using index "unique_personne_avatar";

alter table "public"."familles" add constraint "familles_login_token_key" UNIQUE using index "familles_login_token_key";

alter table "public"."familles" add constraint "users_auth_uuid_fkey" FOREIGN KEY (auth_uuid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."familles" validate constraint "users_auth_uuid_fkey";

alter table "public"."familles" add constraint "users_personne_principale_fkey" FOREIGN KEY (personne_principale) REFERENCES public.personnes(id) not valid;

alter table "public"."familles" validate constraint "users_personne_principale_fkey";

alter table "public"."musiques" add constraint "check_titre_not_empty" CHECK (((titre IS NULL) OR (length(TRIM(BOTH FROM titre)) > 0))) not valid;

alter table "public"."musiques" validate constraint "check_titre_not_empty";

alter table "public"."musiques" add constraint "check_valid_url" CHECK (((lien IS NULL) OR (lien ~* '^https?://.*'::text))) not valid;

alter table "public"."musiques" validate constraint "check_valid_url";

alter table "public"."musiques" add constraint "musiques_personne_id_fkey" FOREIGN KEY (personne_id) REFERENCES public.personnes(id) ON DELETE CASCADE not valid;

alter table "public"."musiques" validate constraint "musiques_personne_id_fkey";

alter table "public"."musiques" add constraint "musiques_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))) not valid;

alter table "public"."musiques" validate constraint "musiques_status_check";

alter table "public"."personnes" add constraint "check_email_format" CHECK (((email IS NULL) OR (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text))) not valid;

alter table "public"."personnes" validate constraint "check_email_format";

alter table "public"."personnes" add constraint "check_nom_not_empty" CHECK (((nom IS NOT NULL) AND (length(TRIM(BOTH FROM nom)) > 0))) not valid;

alter table "public"."personnes" validate constraint "check_nom_not_empty";

alter table "public"."personnes" add constraint "check_prenom_not_empty" CHECK (((prenom IS NOT NULL) AND (length(TRIM(BOTH FROM prenom)) > 0))) not valid;

alter table "public"."personnes" validate constraint "check_prenom_not_empty";

alter table "public"."personnes" add constraint "personnes_famille_id_fkey" FOREIGN KEY (famille_id) REFERENCES public.familles(id) ON DELETE CASCADE not valid;

alter table "public"."personnes" validate constraint "personnes_famille_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.current_user_uuid()
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    SELECT COALESCE((SELECT auth.uid()), '00000000-0000-0000-0000-000000000000'::uuid);
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_avatar_for_personne(p_personne_id bigint)
 RETURNS public.avatars
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    existing_avatar avatars;
BEGIN
    -- Chercher un avatar existant
    SELECT * INTO existing_avatar
    FROM avatars
    WHERE personne_id = p_personne_id;
    
    -- Si pas d'avatar, en créer un
    IF existing_avatar IS NULL THEN
        INSERT INTO avatars (personne_id)
        VALUES (p_personne_id)
        RETURNING * INTO existing_avatar;
    END IF;
    
    RETURN existing_avatar;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_avatar_for_personne(p_personne_id integer)
 RETURNS public.avatars
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_avatar public.avatars;
begin
  select * into v_avatar from public.avatars where personne_id = p_personne_id limit 1;
  if not found then
    insert into public.avatars(personne_id)
    values (p_personne_id)
    returning * into v_avatar;
  end if;
  return v_avatar;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_admin_stats()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    result jsonb := '{}';
BEGIN
    -- Vérifier que l'utilisateur est admin
    IF NOT is_admin() THEN
        RAISE EXCEPTION 'Accès refusé';
    END IF;
    
    -- Construire les statistiques
    SELECT jsonb_build_object(
        'familles', (SELECT COUNT(*) FROM familles),
        'personnes', (SELECT COUNT(*) FROM personnes),
        'avatars_configures', (SELECT COUNT(*) FROM avatars WHERE personne_id IS NOT NULL),
        'musiques_totales', (SELECT COUNT(*) FROM musiques),
        'confirmations', jsonb_build_object(
            'reception', (SELECT COUNT(*) FROM personnes WHERE present_reception = true),
            'repas', (SELECT COUNT(*) FROM personnes WHERE present_repas = true),
            'soiree', (SELECT COUNT(*) FROM personnes WHERE present_soiree = true)
        ),
        'invitations_par_type', (
            SELECT jsonb_object_agg(invite_pour, cnt)
            FROM (
                SELECT invite_pour, COUNT(*) as cnt
                FROM personnes 
                GROUP BY invite_pour
            ) subq
        )
    ) INTO result;
    
    RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_avatar_for_token(p_token text, p_personne_id bigint)
 RETURNS TABLE(id bigint, personne_id bigint, seed text, options jsonb, created_at timestamp with time zone, updated_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  fam RECORD;
BEGIN
  SELECT * INTO fam FROM get_famille_by_token(p_token);
  IF fam IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT a.id, a.personne_id, a.seed, a.options, a.created_at, a.updated_at
  FROM avatars a
  WHERE a.personne_id = p_personne_id
    AND EXISTS (
      SELECT 1 FROM personnes p WHERE p.id = a.personne_id AND p.famille_id = fam.id
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_famille_by_token(p_token text)
 RETURNS SETOF public.familles
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select *
  from public.familles
  where login_token = p_token
  limit 1
$function$
;

CREATE OR REPLACE FUNCTION public.get_personnes_by_famille(p_famille_id bigint)
 RETURNS TABLE(id bigint, nom text, prenom text, invite_reception boolean, present_reception boolean, invite_repas boolean, present_repas boolean, invite_soiree boolean, present_soiree boolean)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    id,
    nom,
    prenom,
    COALESCE(invite_reception, false)    AS invite_reception,
    COALESCE(present_reception, false)   AS present_reception,
    COALESCE(invite_repas, false)        AS invite_repas,
    COALESCE(present_repas, false)       AS present_repas,
    COALESCE(invite_soiree, false)       AS invite_soiree,
    COALESCE(present_soiree, false)      AS present_soiree
  FROM public.personnes
  WHERE famille_id = p_famille_id
  ORDER BY id;
$function$
;

CREATE OR REPLACE FUNCTION public.get_stats_admin()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_rsvp_total int := 0;
  v_rsvp_apero int := 0;
  v_rsvp_repas int := 0;
  v_rsvp_soiree int := 0;
  v_photos_pending int := 0;
  v_photos_approved int := 0;
  v_photos_rejected int := 0;
  v_musiques_pending int := 0;
  v_musiques_approved int := 0;
  v_musiques_rejected int := 0;
begin
  -- RSVP (optional)
  if to_regclass('public.rsvp') is not null then
    select count(*) into v_rsvp_total from public.rsvp;
    select count(*) into v_rsvp_apero from public.rsvp where coalesce(pour_apero,false) is true;
    select count(*) into v_rsvp_repas from public.rsvp where coalesce(pour_repas,false) is true;
    select count(*) into v_rsvp_soiree from public.rsvp where coalesce(pour_soiree,false) is true;
  end if;

  -- Photos (optional)
  if to_regclass('public.photos') is not null then
    select count(*) into v_photos_pending from public.photos where status = 'pending';
    select count(*) into v_photos_approved from public.photos where status = 'approved';
    select count(*) into v_photos_rejected from public.photos where status = 'rejected';
  end if;

  -- Musiques (optional)
  if to_regclass('public.musiques') is not null then
    select count(*) into v_musiques_pending from public.musiques where status = 'pending';
    select count(*) into v_musiques_approved from public.musiques where status = 'approved';
    select count(*) into v_musiques_rejected from public.musiques where status = 'rejected';
  end if;

  return jsonb_build_object(
    'rsvp_total', v_rsvp_total,
    'rsvp_apero', v_rsvp_apero,
    'rsvp_repas', v_rsvp_repas,
    'rsvp_soiree', v_rsvp_soiree,
    'photos_pending', v_photos_pending,
    'photos_approved', v_photos_approved,
    'photos_rejected', v_photos_rejected,
    'musiques_pending', v_musiques_pending,
    'musiques_approved', v_musiques_approved,
    'musiques_rejected', v_musiques_rejected
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_by_token(p_token text)
 RETURNS TABLE(id bigint, login_token text, auth_uuid uuid)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select u.id, u.login_token, u.auth_uuid
  from public.users u
  where u.login_token = p_token
  limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- If profile already exists, skip
  if exists (select 1 from public.profiles where id = new.id) then
    return new;
  end if;
  insert into public.profiles(id, role) values (new.id, 'invite');
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_famille()
 RETURNS SETOF public.familles
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  insert into public.familles default values returning *;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    SELECT COALESCE((SELECT auth.jwt()) ->> 'role' = 'admin', false);
$function$
;

CREATE OR REPLACE FUNCTION public.list_personnes_by_token(p_token text)
 RETURNS SETOF public.personnes
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select p.*
  from public.personnes p
  join public.familles f on f.id = p.famille_id
  where f.login_token = p_token
  order by p.id asc
$function$
;

CREATE OR REPLACE FUNCTION public.mcp_describe_table(p_table text, p_schema text DEFAULT 'public'::text)
 RETURNS json
 LANGUAGE sql
 STABLE
AS $function$
  select coalesce(
    json_agg(row_to_json(c)), '[]'::json
  )
  from (
    select
      c.ordinal_position,
      c.column_name,
      c.data_type,
      c.is_nullable,
      c.character_maximum_length,
      c.numeric_precision,
      c.numeric_scale,
      c.column_default
    from information_schema.columns c
    where c.table_schema = p_schema and c.table_name = p_table
    order by c.ordinal_position
  ) c;
$function$
;

CREATE OR REPLACE FUNCTION public.mcp_list_tables(p_schema text DEFAULT 'public'::text)
 RETURNS json
 LANGUAGE sql
 STABLE
AS $function$
  select coalesce(
    json_agg(row_to_json(t)), '[]'::json
  )
  from (
    select table_schema, table_name
    from information_schema.tables
    where table_schema = p_schema
      and table_type = 'BASE TABLE'
    order by table_name
  ) t;
$function$
;

CREATE OR REPLACE FUNCTION public.record_rsvp(p_famille_id integer, p_payload jsonb)
 RETURNS TABLE(updated integer, errors jsonb)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  item jsonb;
  personne_id int;
  updated_count int := 0;
  errs jsonb := '[]'::jsonb;
BEGIN
  IF p_payload IS NULL THEN
    RETURN QUERY SELECT updated_count, errs;
    RETURN;
  END IF;

  FOR item IN SELECT * FROM jsonb_array_elements(p_payload)
  LOOP
    BEGIN
      IF NOT (item ? 'personne_id') THEN
        errs := errs || jsonb_build_array(jsonb_build_object('item', item, 'error', 'missing_personne_id'));
        CONTINUE;
      END IF;

      personne_id := (item->>'personne_id')::int;

      -- Only update the provided keys; do NOT touch non-existing columns
      UPDATE personnes
      SET
        present_reception = CASE WHEN item ? 'present_reception' THEN (item->>'present_reception')::boolean ELSE present_reception END,
        present_repas     = CASE WHEN item ? 'present_repas'     THEN (item->>'present_repas')::boolean     ELSE present_repas     END,
        present_soiree    = CASE WHEN item ? 'present_soiree'    THEN (item->>'present_soiree')::boolean    ELSE present_soiree    END
      WHERE id = personne_id
        AND famille_id = p_famille_id;

      IF FOUND THEN
        updated_count := updated_count + 1;
      ELSE
        errs := errs || jsonb_build_array(jsonb_build_object('personne_id', personne_id, 'error', 'not_found_or_not_belong_to_famille'));
      END IF;

    EXCEPTION WHEN others THEN
      errs := errs || jsonb_build_array(jsonb_build_object('item', item, 'error', sqlerrm));
    END;
  END LOOP;

  RETURN QUERY SELECT updated_count, errs;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_music_status(p_id integer, p_status text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if p_status not in ('pending','approved','rejected') then
    raise exception 'invalid status %', p_status using errcode = '22023';
  end if;
  update public.musiques set status = p_status where id = p_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_photo_status(p_id integer, p_status text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if p_status not in ('pending','approved','rejected') then
    raise exception 'invalid status %', p_status using errcode = '22023';
  end if;
  update public.photos set status = p_status where id = p_id;
end;
$function$
;

create or replace view "public"."stats_rapides" as  SELECT ( SELECT count(*) AS count
           FROM public.familles) AS nb_familles,
    ( SELECT count(*) AS count
           FROM public.personnes) AS nb_personnes,
    ( SELECT count(*) AS count
           FROM public.avatars) AS nb_avatars_crees,
    ( SELECT count(*) AS count
           FROM public.musiques) AS nb_musiques_proposees,
    ( SELECT count(*) AS count
           FROM public.personnes
          WHERE (personnes.present_reception = true)) AS confirmations_reception,
    ( SELECT count(*) AS count
           FROM public.personnes
          WHERE (personnes.present_repas = true)) AS confirmations_repas,
    ( SELECT count(*) AS count
           FROM public.personnes
          WHERE (personnes.present_soiree = true)) AS confirmations_soiree;


CREATE OR REPLACE FUNCTION public.submit_music(p_value jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- first track
  if coalesce(trim((p_value->>'artist1')), '') <> '' or coalesce(trim((p_value->>'title1')), '') <> '' then
    insert into public.musiques(auteur, titre, lien, commentaire)
    values (
      nullif(p_value->>'artist1', ''),
      nullif(p_value->>'title1', ''),
      nullif(p_value->>'link1', ''),
      nullif(p_value->>'comment1', '')
    );
  end if;
  -- second track
  if coalesce(trim((p_value->>'artist2')), '') <> '' or coalesce(trim((p_value->>'title2')), '') <> '' then
    insert into public.musiques(auteur, titre, lien, commentaire)
    values (
      nullif(p_value->>'artist2', ''),
      nullif(p_value->>'title2', ''),
      nullif(p_value->>'link2', ''),
      nullif(p_value->>'comment2', '')
    );
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.tg_set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.touch_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_avatar_choices(p_personne_id bigint, p_selections jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    avatar_record avatars;
    category_key text;
    asset_id_val bigint;
BEGIN
    -- Assurer qu'un avatar existe
    SELECT * INTO avatar_record FROM ensure_avatar_for_personne(p_personne_id);
    
    -- Supprimer les choix existants
    DELETE FROM avatar_asset_choices WHERE avatar_id = avatar_record.id;
    
    -- Insérer les nouveaux choix
    FOR category_key IN SELECT jsonb_object_keys(p_selections)
    LOOP
        asset_id_val := (p_selections ->> category_key)::bigint;
        
        INSERT INTO avatar_asset_choices (avatar_id, category, asset_id)
        VALUES (avatar_record.id, category_key::avatar_category, asset_id_val);
    END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_avatar_choices(p_personne_id integer, p_selections jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_avatar_id int;
  v_key text;
  v_val text;
begin
  select id into v_avatar_id from public.avatars where personne_id = p_personne_id;
  if v_avatar_id is null then
    insert into public.avatars(personne_id) values (p_personne_id) returning id into v_avatar_id;
  end if;

  -- Iterate jsonb object and upsert rows
  for v_key, v_val in
    select key, value::text from jsonb_each(p_selections)
  loop
    insert into public.avatar_asset_choices(avatar_id, category, asset_id)
    values (v_avatar_id, v_key, v_val)
    on conflict (avatar_id, category)
    do update set asset_id = excluded.asset_id;
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_avatar_for_token(p_token text, p_personne_id bigint, p_seed text, p_options jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  fam RECORD;
  result jsonb;
BEGIN
  -- validate token using existing SECURITY DEFINER RPC get_famille_by_token
  SELECT * INTO fam FROM get_famille_by_token(p_token);
  IF fam IS NULL THEN
    RAISE EXCEPTION 'invalid_token';
  END IF;

  -- ensure the personne belongs to the famille
  IF NOT EXISTS (SELECT 1 FROM personnes WHERE id = p_personne_id AND famille_id = fam.id) THEN
    RAISE EXCEPTION 'personne_not_in_famille';
  END IF;

  INSERT INTO avatars(personne_id, seed, options)
  VALUES (p_personne_id, p_seed, COALESCE(p_options, '{}'::jsonb))
  ON CONFLICT (personne_id) DO UPDATE
    SET seed = EXCLUDED.seed,
        options = EXCLUDED.options,
        updated_at = now()
  RETURNING to_jsonb(avatars.*) INTO result;

  RETURN result;
END;
$function$
;

grant delete on table "public"."app_secrets" to "anon";

grant insert on table "public"."app_secrets" to "anon";

grant references on table "public"."app_secrets" to "anon";

grant select on table "public"."app_secrets" to "anon";

grant trigger on table "public"."app_secrets" to "anon";

grant truncate on table "public"."app_secrets" to "anon";

grant update on table "public"."app_secrets" to "anon";

grant delete on table "public"."app_secrets" to "authenticated";

grant insert on table "public"."app_secrets" to "authenticated";

grant references on table "public"."app_secrets" to "authenticated";

grant select on table "public"."app_secrets" to "authenticated";

grant trigger on table "public"."app_secrets" to "authenticated";

grant truncate on table "public"."app_secrets" to "authenticated";

grant update on table "public"."app_secrets" to "authenticated";

grant delete on table "public"."app_secrets" to "service_role";

grant insert on table "public"."app_secrets" to "service_role";

grant references on table "public"."app_secrets" to "service_role";

grant select on table "public"."app_secrets" to "service_role";

grant trigger on table "public"."app_secrets" to "service_role";

grant truncate on table "public"."app_secrets" to "service_role";

grant update on table "public"."app_secrets" to "service_role";

grant delete on table "public"."audit_log" to "anon";

grant insert on table "public"."audit_log" to "anon";

grant references on table "public"."audit_log" to "anon";

grant select on table "public"."audit_log" to "anon";

grant trigger on table "public"."audit_log" to "anon";

grant truncate on table "public"."audit_log" to "anon";

grant update on table "public"."audit_log" to "anon";

grant delete on table "public"."audit_log" to "authenticated";

grant insert on table "public"."audit_log" to "authenticated";

grant references on table "public"."audit_log" to "authenticated";

grant select on table "public"."audit_log" to "authenticated";

grant trigger on table "public"."audit_log" to "authenticated";

grant truncate on table "public"."audit_log" to "authenticated";

grant update on table "public"."audit_log" to "authenticated";

grant delete on table "public"."audit_log" to "service_role";

grant insert on table "public"."audit_log" to "service_role";

grant references on table "public"."audit_log" to "service_role";

grant select on table "public"."audit_log" to "service_role";

grant trigger on table "public"."audit_log" to "service_role";

grant truncate on table "public"."audit_log" to "service_role";

grant update on table "public"."audit_log" to "service_role";

grant delete on table "public"."avatars" to "anon";

grant insert on table "public"."avatars" to "anon";

grant references on table "public"."avatars" to "anon";

grant select on table "public"."avatars" to "anon";

grant trigger on table "public"."avatars" to "anon";

grant truncate on table "public"."avatars" to "anon";

grant update on table "public"."avatars" to "anon";

grant delete on table "public"."avatars" to "authenticated";

grant insert on table "public"."avatars" to "authenticated";

grant references on table "public"."avatars" to "authenticated";

grant select on table "public"."avatars" to "authenticated";

grant trigger on table "public"."avatars" to "authenticated";

grant truncate on table "public"."avatars" to "authenticated";

grant update on table "public"."avatars" to "authenticated";

grant delete on table "public"."avatars" to "service_role";

grant insert on table "public"."avatars" to "service_role";

grant references on table "public"."avatars" to "service_role";

grant select on table "public"."avatars" to "service_role";

grant trigger on table "public"."avatars" to "service_role";

grant truncate on table "public"."avatars" to "service_role";

grant update on table "public"."avatars" to "service_role";

grant delete on table "public"."familles" to "anon";

grant insert on table "public"."familles" to "anon";

grant references on table "public"."familles" to "anon";

grant select on table "public"."familles" to "anon";

grant trigger on table "public"."familles" to "anon";

grant truncate on table "public"."familles" to "anon";

grant update on table "public"."familles" to "anon";

grant delete on table "public"."familles" to "authenticated";

grant insert on table "public"."familles" to "authenticated";

grant references on table "public"."familles" to "authenticated";

grant select on table "public"."familles" to "authenticated";

grant trigger on table "public"."familles" to "authenticated";

grant truncate on table "public"."familles" to "authenticated";

grant update on table "public"."familles" to "authenticated";

grant delete on table "public"."familles" to "service_role";

grant insert on table "public"."familles" to "service_role";

grant references on table "public"."familles" to "service_role";

grant select on table "public"."familles" to "service_role";

grant trigger on table "public"."familles" to "service_role";

grant truncate on table "public"."familles" to "service_role";

grant update on table "public"."familles" to "service_role";

grant delete on table "public"."musiques" to "anon";

grant insert on table "public"."musiques" to "anon";

grant references on table "public"."musiques" to "anon";

grant select on table "public"."musiques" to "anon";

grant trigger on table "public"."musiques" to "anon";

grant truncate on table "public"."musiques" to "anon";

grant update on table "public"."musiques" to "anon";

grant delete on table "public"."musiques" to "authenticated";

grant insert on table "public"."musiques" to "authenticated";

grant references on table "public"."musiques" to "authenticated";

grant select on table "public"."musiques" to "authenticated";

grant trigger on table "public"."musiques" to "authenticated";

grant truncate on table "public"."musiques" to "authenticated";

grant update on table "public"."musiques" to "authenticated";

grant delete on table "public"."musiques" to "service_role";

grant insert on table "public"."musiques" to "service_role";

grant references on table "public"."musiques" to "service_role";

grant select on table "public"."musiques" to "service_role";

grant trigger on table "public"."musiques" to "service_role";

grant truncate on table "public"."musiques" to "service_role";

grant update on table "public"."musiques" to "service_role";

grant delete on table "public"."personnes" to "anon";

grant insert on table "public"."personnes" to "anon";

grant references on table "public"."personnes" to "anon";

grant select on table "public"."personnes" to "anon";

grant trigger on table "public"."personnes" to "anon";

grant truncate on table "public"."personnes" to "anon";

grant update on table "public"."personnes" to "anon";

grant delete on table "public"."personnes" to "authenticated";

grant insert on table "public"."personnes" to "authenticated";

grant references on table "public"."personnes" to "authenticated";

grant select on table "public"."personnes" to "authenticated";

grant trigger on table "public"."personnes" to "authenticated";

grant truncate on table "public"."personnes" to "authenticated";

grant update on table "public"."personnes" to "authenticated";

grant delete on table "public"."personnes" to "service_role";

grant insert on table "public"."personnes" to "service_role";

grant references on table "public"."personnes" to "service_role";

grant select on table "public"."personnes" to "service_role";

grant trigger on table "public"."personnes" to "service_role";

grant truncate on table "public"."personnes" to "service_role";

grant update on table "public"."personnes" to "service_role";


  create policy "audit_log_admin_only"
  on "public"."audit_log"
  as permissive
  for all
  to public
using (public.is_admin());



  create policy "Avatars: lecture par famille ou admin"
  on "public"."avatars"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM (public.personnes p
     JOIN public.familles f ON ((p.famille_id = f.id)))
  WHERE ((p.id = avatars.personne_id) AND ((f.auth_uuid = ( SELECT auth.uid() AS uid)) OR ((( SELECT auth.jwt() AS jwt) ->> 'role'::text) = 'admin'::text))))));



  create policy "Avatars: modification par famille ou admin"
  on "public"."avatars"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM (public.personnes p
     JOIN public.familles f ON ((p.famille_id = f.id)))
  WHERE ((p.id = avatars.personne_id) AND ((f.auth_uuid = ( SELECT auth.uid() AS uid)) OR ((( SELECT auth.jwt() AS jwt) ->> 'role'::text) = 'admin'::text))))));



  create policy "Musiques: insertion par famille"
  on "public"."musiques"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM (public.personnes p
     JOIN public.familles f ON ((p.famille_id = f.id)))
  WHERE ((p.id = musiques.personne_id) AND (f.auth_uuid = ( SELECT auth.uid() AS uid))))));



  create policy "Musiques: lecture par famille ou admin"
  on "public"."musiques"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM (public.personnes p
     JOIN public.familles f ON ((p.famille_id = f.id)))
  WHERE ((p.id = musiques.personne_id) AND ((f.auth_uuid = ( SELECT auth.uid() AS uid)) OR ((( SELECT auth.jwt() AS jwt) ->> 'role'::text) = 'admin'::text))))));



  create policy "Musiques: modification par admin"
  on "public"."musiques"
  as permissive
  for update
  to public
using (((( SELECT auth.jwt() AS jwt) ->> 'role'::text) = 'admin'::text));



  create policy "Musiques: suppression par admin"
  on "public"."musiques"
  as permissive
  for delete
  to public
using (((( SELECT auth.jwt() AS jwt) ->> 'role'::text) = 'admin'::text));



  create policy "Allow select for same famille"
  on "public"."personnes"
  as permissive
  for select
  to public
using ((famille_id = ((auth.jwt() ->> 'famille_id'::text))::integer));


CREATE TRIGGER trg_touch_updated_at BEFORE UPDATE ON public.avatars FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TRIGGER on_auth_user_created_insert_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();


