name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build Angular app
        run: npm run build -- --configuration production --base-href=/faire-part/
      - name: Vérification du build
        run: ls -l dist/faire-part
      - name: Copie du fallback SPA (404.html)
        run: cp -f dist/faire-part/index.html dist/faire-part/404.html
      - name: Injection des clés Supabase dans les meta tags
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          for f in dist/faire-part/index.html dist/faire-part/404.html; do
            if grep -q 'name="supabase-url"' "$f"; then
              sed -i "s|<meta name=\"supabase-url\" content=\"[^\"]*\">|<meta name=\"supabase-url\" content=\"${SUPABASE_URL}\">|g" $f
            else
              sed -i "1,/<\/head>/s|</head>|  <meta name=\"supabase-url\" content=\"${SUPABASE_URL}\">\n</head>|" $f
            fi
            if grep -q 'name="supabase-anon-key"' "$f"; then
              sed -i "s|<meta name=\"supabase-anon-key\" content=\"[^\"]*\">|<meta name=\"supabase-anon-key\" content=\"${SUPABASE_ANON_KEY}\">|g" $f
            else
              sed -i "1,/<\/head>/s|</head>|  <meta name=\"supabase-anon-key\" content=\"${SUPABASE_ANON_KEY}\">\n</head>|" $f
            fi
          done
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/faire-part

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Déploiement sur GitHub Pages
        uses: actions/deploy-pages@v1
